name: Test

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main-build'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

  functional_test:
    runs-on: ubuntu-18.04
    if: github.ref != 'refs/heads/main-build'

    steps:
      - uses: actions/checkout@v2

      - name: Install JS dependencies
        run: npm ci

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          spec: cypress/integration/*.spec.ts

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
